yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
# Issues with expo
  expo@*:
    dependencies:
      react: " 16.11.x"
      react-native: "*"
      url-parse: "*" # added for yarn start with metro pnp enabled
  "@expo/config@*":
    dependencies:
      glob: "*"
      "@babel/core": "*"
  "@expo/plist@*":
    dependencies:
      invariant: "*"
  "@expo/dev-tools@*":
    dependencies:
      "@expo/spawn-async": "*"
  expo-cli@*:
    dependencies:
      react-dev-utils: "*"
  "@react-native-community/cli-platform-ios@*":
    dependencies:
      lodash: "*"
      glob: "*" # added for yarn ios after ejection
  "@react-native-community/cli-debugger-ui@*":
    dependencies:
      "@babel/runtime": "*"
  jest-worker@*:
    dependencies:
      metro: "0.58.0"
  glob-promise@*:
    dependencies:
      glob: "*"
  "@babel/plugin-transform-block-scoping@*":
    dependencies:
      "@babel/core": "*"
  babel-preset-expo@*:
    dependencies:
      "@babel/core": "*"
# issues with yarn eject
  pacote@*:
    dependencies:
      rimraf: "*"
      unique-filename: "*"
  "@expo/package-manager@*":
    dependencies:
      chalk: "*"
# issues after ejection
  "@react-native-community/cli-platform-android@*":
    dependencies:
      glob: "*"
  metro@*:
    dependencies:
      "@babel/runtime": "*"
# issues after metro pnp is enabled
  expo-constants@*:
    dependencies:
      "@babel/runtime": "*"
      "@unimodules/core": "*"
  "@unimodules/core@*":
    dependencies:
      "@babel/runtime": "*"
      "@unimodules/react-native-adapter": "*"
      react-native: "*"
  react-native@*:
    dependencies:
      metro: "0.58.0"
      react: "*"
  "@unimodules/react-native-adapter@*":
    dependencies:
      "@babel/runtime": "*"
      react: "*"
  pretty-format@*:
    dependencies:
      "@babel/runtime": "*"
  abort-controller@*:
    dependencies:
      "@babel/runtime": "*"
  expo-asset@*:
    dependencies:
      "@babel/runtime": "*"
      "@unimodules/core": "*"
      react-native: "*"
      expo-constants: "*"
      expo-file-system: "*"
  object-assign@*:
    dependencies:
      "@babel/runtime": "*"
  ansi-regex@*:
    dependencies:
      "@babel/runtime": "*"
  expo-file-system@*:
    dependencies:
      "@babel/runtime": "*"
      "@unimodules/core": "*"
      react-native: "*"
  react-devtools-core@*:
    dependencies:
      "@babel/runtime": "*"
  safe-buffer@*:
    dependencies:
      buffer: "*"
  inherits@*:
    dependencies:
      util: "*"
  asn1.js@*:
    dependencies:
      vm: "*"
      buffer: "*"
  readable-stream@*:
    dependencies:
      "@babel/runtime": "*"
      stream: "*"
      buffer: "*"
      events: "*"
      util: "*"
  bn.js@*:
    dependencies:
      buffer: "*"
  stream@*:
    dependencies:
      emitter: "*"
  util-deprecate@*:
    dependencies:
      util: "*"
  react-native-randombytes@*:
    dependencies:
      react-native: "*"
# trying to get patches to work
  metro-config@*:
    dependencies:
      metro: "0.58.0"


